[build]
builder = "nixpacks"
buildCommand = "npm install && cd crane-section && npm install && npm run deploy && cd .."

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
